# Site settings
title: Francisco Blanco-Silva
email: francisco.blanco.silva@gmail.com
description: >
  Useless math is useful math. It can be used to generate more useless math.
baseurl: # the subpath of your site, e.g. /blog/
# paginate: 10
url: "http://blancosilva.github.io" # the base hostname & protocol for your site
avatar: https://farm6.staticflickr.com/5131/5393012839_cf3ccae561_o_d.png
twitter_username: eseprimo
github_username:  blancosilva
stackoverflow_username: users/4159070/francisco-javier-blanco-silva
facebook_username: eseprimo
flickr_username: eseprimo
linkedin_username: francisco-blanco-silva/1b/887/870
comments:
  provider: disqus
  disqus:
    short_name: blancosilva

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
